[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = [
  "-c",
  "npx tailwindcss -i ./styles/tailwind.css -o ./dist/.stage/styles.css",
]

[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri"]

[serve]
address = "127.0.0.1"
port = 1420
open = false
